# Generated by Django 4.2.7 on 2023-11-23 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="status",
            field=models.CharField(
                choices=[
                    ("Disponível", "Disponível"),
                    ("Reservado", "Reservado"),
                    ("Retirado", "Retirado"),
                ],
                default="Disponível",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="books",
            name="reservations",
            field=models.ManyToManyField(blank=True, to="main.reservation"),
        ),
    ]
