# Generated by Django 4.2.7 on 2023-11-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_books_status_reservation_books_reservations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(),
        ),
    ]
