# Generated by Django 4.2.7 on 2023-11-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_reservation_reservation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
