# Generated by Django 4.2.7 on 2023-11-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_reservation_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="book",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="main.books"
            ),
        ),
    ]
